version: '3.5'
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.letsencrypt.acme.email=beau@lioncode.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./docker-conf/traefik.yml:/etc/traefik/traefik.yml
    labels:
      - "traefik.enable=true"
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      # Optional - alternative address used for autodiscovery
      #   - JELLYFIN_PublishedServerUrl=http://example.com
    volumes:
      - /mnt/1tb-hdd/server/server-config/config/jellyfin:/config
      - /mnt/1tb-hdd/server/server-config/cache:/cache
      - /mnt/1tb-hdd/server/Anime:/anime
      - /mnt/1tb-hdd/server/Movies:/movies
      - /mnt/wd-black/server/anime/:/otherAnime
    ports:
      - 8920:8920
    restart: 'unless-stopped'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`beautaapken.duckdns.org`) || Host(`beautaapken.duckdns.org`) && PathPrefix(`/jellyfin`)"
      # Host(`beautaapken.duckdns.org`) && PathPrefix(`/jellyfin`)"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
