services:
# Jellyfin
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - DOCKER_MODS=ghcr.io/intro-skipper/intro-skipper-docker-mod
      # Optional - alternative address used for autodiscovery
      #   - JELLYFIN_PublishedServerUrl=http://192.168.1.132
    volumes:
      - ./config/jellyfin:/config
      - ./cache:/cache
      - /mnt/1tb-hdd/server:/1tb-hdd
      - /mnt/wd-black/server:/wd-black
      - /mnt/18tb-exo:/18tb-exo
    ports:
      - 8920:8920
    restart: always
    group_add:
      - "989" # Change this to match your "render" host group id (getent group render | cut -d: -f3) (group may also be video or input)
    devices:
      - /dev/dri:/dev/dri # May need more specific like /dev/dri/renderD128
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`beautaapken.duckdns.org`)"
      #- "traefik.http.routers.jellyfin.rule=Host(`beautaapken.duckdns.org`) && PathPrefix(`/jellyfin`)"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]
