services:
# Jellyfin
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      # Optional - alternative address used for autodiscovery
      #   - JELLYFIN_PublishedServerUrl=http://example.com
    volumes:
      - ./config/jellyfin:/config
      - ./cache:/cache
      - /mnt/1tb-hdd/server:/1tb-hdd
      - /mnt/wd-black/server:/wd-black
      - /mnt/18tb-exo:/18tb-exo
    ports:
      - 8920:8920
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`beautaapken.duckdns.org`)"
      #- "traefik.http.routers.jellyfin.rule=Host(`beautaapken.duckdns.org`) && PathPrefix(`/jellyfin`)"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
