services:
  materialious:
    image: wardpearce/materialious-full:1.17.1
    container_name: materialious
    restart: unless-stopped
    environment:
      PUID: ${PGID}
      PGID: ${PUID}
      TZ: ${TZ}
      COOKIE_SECRET: ${MATERIALIOUS_COOKIE_SECRET}
      DATABASE_CONNECTION_URI: "sqlite:///materialious-data/materialious.db"
      PUBLIC_PLAYER_ID: ""
      PUBLIC_INTERNAL_AUTH: "true"
      PUBLIC_REQUIRE_AUTH: "true"
      PUBLIC_REGISTRATION_ALLOWED: "false"
      PUBLIC_ADMIN_USERNAMES: ${MATERIALIOUS_ADMINS}
      PUBLIC_CAPTCHA_DISABLED: "false"
      PUBLIC_RATE_LIMIT_DISABLED: "true"
      WHITELIST_BASE_DOMAIN: ""
      PROXY_TRUST_CA: ""
      PUBLIC_DANGEROUS_ALLOW_ANY_PROXY: "false"
      PUBLIC_DEFAULT_INVIDIOUS_INSTANCE: ""
      PUBLIC_DEFAULT_RETURNYTDISLIKES_INSTANCE: "https://ryd-proxy:3003"
      PUBLIC_DEFAULT_SPONSERBLOCK_INSTANCE: "https://sponsor.ajay.app"
      PUBLIC_DEFAULT_DEARROW_INSTANCE: "https://sponsor.ajay.app"
      PUBLIC_DEFAULT_DEARROW_THUMBNAIL_INSTANCE: "https://dearrow-thumb.ajay.app"
      PUBLIC_DEFAULT_SETTINGS: '{"themeColor": "#2596be","region": "NL"}'
    volumes:
      - ./data/materialious:/materialious-data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.materialious.rule=Host(`materialious.${HOST}`)"
      - "traefik.http.routers.materialious.service=materialious"
      - "traefik.http.routers.materialious.entrypoints=https"
      - "traefik.http.routers.materialious.tls=true"
      - "traefik.http.routers.materialious.tls.certresolver=letsencrypt"
      - "traefik.http.services.materialious.loadbalancer.server.port=3000"


  tor-proxy:
    image: 1337kavin/alpine-tor:latest
    container_name: tor-proxy
    restart: unless-stopped
    environment:
      - tors=15

  ryd-proxy:
    image: 1337kavin/ryd-proxy:latest
    container_name: ryd-proxy
    restart: unless-stopped
    depends_on:
      - tor-proxy
    environment:
      - PROXY=socks5://tor-proxy:5566
    ports:
      - 3003:3000
