services:
  materialious:
    image: wardpearce/materialious-full:latest
    container_name: materialious
    restart: unless-stopped
    environment:
      PUID: ${PGID}
      PGID: ${PUID}
      TZ: ${TZ}
      COOKIE_SECRET: ${COOKIE_SECRET}
      # Database connectiong URI
      # Not required if PUBLIC_INTERNAL_AUTH is false
      # postgresql, mysql2, mariadb & sqlite supported
      # guide here for URL structure https://docs.preset.io/docs/uri-connection-strings
      DATABASE_CONNECTION_URI: "sqlite:///materialious-data/materialious.db"
      # YouTube player id to use, can be left blank but setting to a older player id may fix 
      # video playback with local video processing.
      # https://youtube-player-ids.nadeko.net
      PUBLIC_PLAYER_ID: ""
      # Use Materialious account system.
      PUBLIC_INTERNAL_AUTH: "true"
      # If Auth is required to use this instance.
      # Should be left as true, otherwise anyone can use Materialious proxy.
      PUBLIC_REQUIRE_AUTH: "true"
      # Allow anyone to register
      PUBLIC_REGISTRATION_ALLOWED: "false"
      # Disable POW Captcha
      PUBLIC_CAPTCHA_DISABLED: "false"
      # Allows you to whitelist additional domains in proxy.
      # Should be comma separated and be the base domain
      # e.g. "youtube.com,google.com" NOT "https://youtube.com,https://videos.google.com"
      WHITELIST_BASE_DOMAIN: ""
      # Specify a path to a certificate to trust, useful when using self-signed certificates.
      PROXY_TRUST_CA: ""
      # Allow any domain in proxy
      # This shouldn't be used unless you KNOW what your doing
      # requires PUBLIC_REGISTRATION_ALLOWED to be false
      # PUBLIC_REQUIRE_AUTH to be true
      # PUBLIC_INTERNAL_AUTH to be true
      # to take effect.
      PUBLIC_DANGEROUS_ALLOW_ANY_PROXY: "false"
      # Optionally set a default Invidious instance
      # This will also whitelist this instance in the proxy.
      PUBLIC_DEFAULT_INVIDIOUS_INSTANCE: ""
      # URL TO RYD (Return YouTube Dislike / https://github.com/Anarios/return-youtube-dislike)
      # Leave blank to disable completely.
      # This will also whitelist this instance in the proxy.
      PUBLIC_DEFAULT_RETURNYTDISLIKES_INSTANCE: "https://returnyoutubedislikeapi.com"
      # URL to Sponsorblock
      # Leave blank to completely disable sponsorblock.
      # This will also whitelist this instance in the proxy.
      PUBLIC_DEFAULT_SPONSERBLOCK_INSTANCE: "https://sponsor.ajay.app"
      # URL to DeArrow
      # This will also whitelist this instance in the proxy.
      PUBLIC_DEFAULT_DEARROW_INSTANCE: "https://sponsor.ajay.app"
      # URL to DeArrow thumbnail instance
      # This will also whitelist this instance in the proxy.
      PUBLIC_DEFAULT_DEARROW_THUMBNAIL_INSTANCE: "https://dearrow-thumb.ajay.app"
      # Look at "Overwriting Materialious defaults" for all the accepted values.
      # This will also whitelist this instance in the proxy.
      PUBLIC_DEFAULT_SETTINGS: '{"themeColor": "#2596be","region": "NL"}'
    volumes:
      - ./data/materialious:/materialious-data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.materialious.rule=Host(`materialious.${HOST}`)"
      - "traefik.http.routers.materialious.service=materialious"
      - "traefik.http.routers.materialious.entrypoints=https"
      - "traefik.http.routers.materialious.tls=true"
      - "traefik.http.routers.materialious.tls.certresolver=letsencrypt"
      - "traefik.http.services.materialious.loadbalancer.server.port=3000"
      - "wud.watch.digest=true"
