services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: signal-cli
    ports:
      - 9080:8080
    environment:
      - MODE=normal #supported modes: json-rpc, native, normal
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
    restart: unless-stopped
    volumes:
      - "./config/signal-cli:/home/.local/share/signal-cli"
    labels:
      - "wud.watch.digest=true"
