services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
#    command:
#      - "--log.level=DEBUG"
#      - "--providers.docker=true"
#      - "--providers.docker.exposedbydefault=false"
#      - "--entrypoints.https.address=:443"
#      - "--entrypoints.minecraft.address=:25565"
#      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
#      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
#      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
#      - "--certificatesresolvers.letsencrypt.acme.email=${EMAIL}"
#      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - 80:80
      - 443:443
      - 25565:25565
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./docker-conf/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - proxy
      - auth
      - devolio
      - sonarr
      - radarr
      - tdarr
      - purgarr
      - prowlarr
      - qbit
      - jellyfin
      - homepage
      - immich
      - radicale
      - minecraft
      - vaultwarden
      - wud
#    environment:
#      - MIJNHOST_API_KEY=${MIJNHOST_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`dashboard.${HOST}`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=https"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PASSWORD}"
      - "traefik.http.routers.traefik-dashboard.middlewares=auth"

networks:
  proxy:
    external: true
  auth:
    external: true
  devolio:
    external: true
  sonarr:
    external: true
  radarr:
    external: true
  tdarr:
    external: true
  purgarr:
    external: true
  prowlarr:
    external: true
  qbit:
    external: true
  jellyfin:
    external: true
  homepage:
    external: true
  immich:
    external: true
  radicale:
    external: true
  minecraft:
    external: true
  vaultwarden:
    external: true
  wud:
    external: true
