version: "3.4"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
      - UMASK_SET=003
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=MyInternalNode
#      - NVIDIA_DRIVER_CAPABILITIES=all
#      - NVIDIA_VISIBLE_DEVICES=all
    group_add:
      - "989"
    volumes:
      - /mnt/1tb-hdd/server:/1tb-hdd
#      - /mnt/wd-black/server/:/wdBlack
      - /mnt/18tb-exo/:/18tb-exos
      - ./config/tdarr/server:/app/server
      - ./config/tdarr/config:/app/configs
      - ./transcode_cache:/temp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tdarr.rule=Host(`tdarr.${HOST}`)"
      - "traefik.http.routers.tdarr.service=tdarr"
      - "traefik.http.routers.tdarr.entrypoints=https"
      - "traefik.http.routers.tdarr.tls=true"
      - "traefik.http.routers.tdarr.tls.certresolver=letsencrypt"
      - "traefik.http.services.tdarr.loadbalancer.server.port=8265"
      - "homepage.group=Transcoding"
      - "homepage.name=Tdarr"
      - "homepage.icon=tdarr.png"
      - "homepage.href=https://tdarr.${HOST}"
      - "homepage.description=Main transcoding service"
      - "homepage.widget.type=tdarr"
      - "homepage.widget.url=http://tdarr:8266"
      - "homepage.widget.key=${TDARR_API_KEY}"
    devices:
      - /dev/dri:/dev/dri
#    deploy:
#      resources:
#        reservations:
#          devices:
#          - driver: nvidia
#            count: all
#            capabilities: [gpu]
