services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    restart: always
    volumes:
      - ./config/vpn:/vpn
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    security_opt:
      - label:disable
    labels:
      - "traefik.enable=false"
      - "wud.watch.digest=true"
