services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    restart: always
    volumes:
      - ./config/vpn:/vpn
    networks:
      - qbit
      - download
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    security_opt:
      - label:disable
    labels:
      - "traefik.enable=false"

networks:
  qbit:
    external: true
  download:
    external: true
